kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
 name: {{ index .Values "remote-mesh-name" }}
 namespace: {{ index .Values "local-mesh-ctl-plane-namespace" }}
spec:
 remote:
   addresses:
   {{- range index .Values "remote-mesh-peering-addresses" }}
     - {{ . | quote }}
   {{- end }}
   discoveryPort: {{ index .Values "remote-mesh-ingress-gateway-nodeport-https-discovery-port-number" }}
   servicePort: {{ index .Values "remote-mesh-ingress-gateway-nodeport-tls-port-number" }}
 gateways:
   ingress:
     name: {{ index .Values "remote-mesh-name" }}-ingress
   egress:
     name: {{ index .Values "remote-mesh-name" }}-egress
 security:
   trustDomain: {{ index .Values "remote-mesh-name" }}.local
   clientID: {{ index .Values "remote-mesh-name" }}.local/ns/{{ index .Values "remote-mesh-ctl-plane-namespace" }}/sa/{{ index .Values "local-mesh-name" }}-egress-service-account
   certificateChain:
     kind: ConfigMap
     name: {{ index .Values "remote-mesh-root-cert-configmap-name" }}