apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: {{ index .Values "local-mesh-bookinfo-namespace" }}
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings